# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import serialstudio_pb2 as serialstudio__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in serialstudio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SerialStudioAPIStub(object):
    """--------------------------------------------------------------------------------------------------
    Service definition
    --------------------------------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteCommand = channel.unary_unary(
                '/serialstudio.SerialStudioAPI/ExecuteCommand',
                request_serializer=serialstudio__pb2.CommandRequest.SerializeToString,
                response_deserializer=serialstudio__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.ExecuteBatch = channel.unary_unary(
                '/serialstudio.SerialStudioAPI/ExecuteBatch',
                request_serializer=serialstudio__pb2.BatchRequest.SerializeToString,
                response_deserializer=serialstudio__pb2.BatchResponse.FromString,
                _registered_method=True)
        self.StreamFrames = channel.unary_stream(
                '/serialstudio.SerialStudioAPI/StreamFrames',
                request_serializer=serialstudio__pb2.StreamRequest.SerializeToString,
                response_deserializer=serialstudio__pb2.FrameBatch.FromString,
                _registered_method=True)
        self.StreamRawData = channel.unary_stream(
                '/serialstudio.SerialStudioAPI/StreamRawData',
                request_serializer=serialstudio__pb2.StreamRequest.SerializeToString,
                response_deserializer=serialstudio__pb2.RawBatch.FromString,
                _registered_method=True)
        self.WriteRawData = channel.unary_unary(
                '/serialstudio.SerialStudioAPI/WriteRawData',
                request_serializer=serialstudio__pb2.RawDataRequest.SerializeToString,
                response_deserializer=serialstudio__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.ListCommands = channel.unary_unary(
                '/serialstudio.SerialStudioAPI/ListCommands',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=serialstudio__pb2.CommandList.FromString,
                _registered_method=True)


class SerialStudioAPIServicer(object):
    """--------------------------------------------------------------------------------------------------
    Service definition
    --------------------------------------------------------------------------------------------------

    """

    def ExecuteCommand(self, request, context):
        """Execute a single registered command by name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteBatch(self, request, context):
        """Execute multiple commands in a single batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFrames(self, request, context):
        """Stream real-time parsed frames in batches (server-streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRawData(self, request, context):
        """Stream raw data from the connected device in batches (server-streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteRawData(self, request, context):
        """Send raw data to the connected device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCommands(self, request, context):
        """List all available API commands with their schemas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SerialStudioAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=serialstudio__pb2.CommandRequest.FromString,
                    response_serializer=serialstudio__pb2.CommandResponse.SerializeToString,
            ),
            'ExecuteBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteBatch,
                    request_deserializer=serialstudio__pb2.BatchRequest.FromString,
                    response_serializer=serialstudio__pb2.BatchResponse.SerializeToString,
            ),
            'StreamFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=serialstudio__pb2.StreamRequest.FromString,
                    response_serializer=serialstudio__pb2.FrameBatch.SerializeToString,
            ),
            'StreamRawData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRawData,
                    request_deserializer=serialstudio__pb2.StreamRequest.FromString,
                    response_serializer=serialstudio__pb2.RawBatch.SerializeToString,
            ),
            'WriteRawData': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteRawData,
                    request_deserializer=serialstudio__pb2.RawDataRequest.FromString,
                    response_serializer=serialstudio__pb2.CommandResponse.SerializeToString,
            ),
            'ListCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCommands,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=serialstudio__pb2.CommandList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serialstudio.SerialStudioAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('serialstudio.SerialStudioAPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SerialStudioAPI(object):
    """--------------------------------------------------------------------------------------------------
    Service definition
    --------------------------------------------------------------------------------------------------

    """

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serialstudio.SerialStudioAPI/ExecuteCommand',
            serialstudio__pb2.CommandRequest.SerializeToString,
            serialstudio__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serialstudio.SerialStudioAPI/ExecuteBatch',
            serialstudio__pb2.BatchRequest.SerializeToString,
            serialstudio__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/serialstudio.SerialStudioAPI/StreamFrames',
            serialstudio__pb2.StreamRequest.SerializeToString,
            serialstudio__pb2.FrameBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRawData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/serialstudio.SerialStudioAPI/StreamRawData',
            serialstudio__pb2.StreamRequest.SerializeToString,
            serialstudio__pb2.RawBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteRawData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serialstudio.SerialStudioAPI/WriteRawData',
            serialstudio__pb2.RawDataRequest.SerializeToString,
            serialstudio__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serialstudio.SerialStudioAPI/ListCommands',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            serialstudio__pb2.CommandList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
